import { type NextRequest, NextResponse } from "next/server"

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const campaign = searchParams.get("campaign") || "ADSPARKX"
    const from = searchParams.get("from")
    const to = searchParams.get("to")
    const filters = searchParams.get("filters")

    // Call details data matching the screenshot exactly
    const callDetailsData = [
      {
        id: "call1",
        callDate: "Jun 17 02:54:07 PM",
        inboundNumber: "TN",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:00:...",
        userQuality: "",
        publisher: "Cobras",
        callerId: "+18654057873",
        timeToAnswer: "00:00:01",
        timeToConnect: "00:00:03",
        revenue: 100.0,
      },
      {
        id: "call2",
        callDate: "Jun 17 02:45:03 PM",
        inboundNumber: "NY",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:06:...",
        userQuality: "",
        publisher: "Scalability",
        callerId: "+17169697812",
        timeToAnswer: "00:00:02",
        timeToConnect: "00:00:03",
        revenue: 100.0,
      },
      {
        id: "call3",
        callDate: "Jun 17 02:03:15 PM",
        inboundNumber: "TX",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:06:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+19795290177",
        timeToAnswer: "00:00:03",
        timeToConnect: "00:00:03",
        revenue: 100.0,
      },
      {
        id: "call4",
        callDate: "Jun 17 03:39:04 PM",
        inboundNumber: "GA",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: true,
        connected: true,
        recording: "00:00:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+17062703023",
        timeToAnswer: "00:00:00",
        timeToConnect: "00:00:03",
        revenue: 100.0,
      },
      {
        id: "call5",
        callDate: "May 15 03:37:56 PM",
        inboundNumber: "AR",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:00:...",
        userQuality: "",
        publisher: "PM",
        callerId: "+18702003379",
        timeToAnswer: "00:00:12",
        timeToConnect: "00:00:04",
        revenue: 90.0,
      },
      {
        id: "call6",
        callDate: "Jan 23 02:12:44 PM",
        inboundNumber: "KS",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: false,
        connected: false,
        recording: "00:00:...",
        userQuality: "",
        publisher: "PP",
        callerId: "+13162376711",
        timeToAnswer: "00:00:03",
        timeToConnect: "00:00:02",
        revenue: 60.0,
      },
      {
        id: "call7",
        callDate: "Jan 23 02:45:06 PM",
        inboundNumber: "AZ",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: false,
        connected: false,
        recording: "00:00:...",
        userQuality: "",
        publisher: "HQ",
        callerId: "+14805066143",
        timeToAnswer: "00:00:06",
        timeToConnect: "00:00:05",
        revenue: 60.0,
      },
      {
        id: "call8",
        callDate: "Jun 13 10:13:20 AM",
        inboundNumber: "FL",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:28:...",
        userQuality: "",
        publisher: "Policy Chat",
        callerId: "+13866781012",
        timeToAnswer: "00:00:00",
        timeToConnect: "00:00:03",
        revenue: 57.12,
      },
      {
        id: "call9",
        callDate: "Feb 04 11:29:22 AM",
        inboundNumber: "SC",
        geoSubDivision: "South Carolina",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:03:...",
        userQuality: "",
        publisher: "Blink - Alex",
        callerId: "+18032006375",
        timeToAnswer: "00:01:18",
        timeToConnect: "00:00:05",
        revenue: 56.0,
      },
      {
        id: "call10",
        callDate: "Jun 16 09:26:55 AM",
        inboundNumber: "CA",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: false,
        connected: false,
        recording: "00:36:...",
        userQuality: "",
        publisher: "Acquire IQ",
        callerId: "+17143916679",
        timeToAnswer: "00:00:09",
        timeToConnect: "00:00:05",
        revenue: 56.0,
      },
      {
        id: "call11",
        callDate: "Jun 25 12:15:14 PM",
        inboundNumber: "NJ",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: false,
        connected: false,
        recording: "00:02:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+12014639813",
        timeToAnswer: "00:00:01",
        timeToConnect: "00:00:13",
        revenue: 55.0,
      },
      {
        id: "call12",
        callDate: "Jun 26 06:06:54 PM",
        inboundNumber: "NY",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: true,
        connected: false,
        recording: "00:51:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+15169136671",
        timeToAnswer: "00:00:00",
        timeToConnect: "00:00:13",
        revenue: 55.0,
      },
      {
        id: "call13",
        callDate: "Jun 26 12:51:34 PM",
        inboundNumber: "CO",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:16:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+13036512771",
        timeToAnswer: "00:00:01",
        timeToConnect: "00:00:11",
        revenue: 55.0,
      },
      {
        id: "call14",
        callDate: "Jun 16 11:10:30 AM",
        inboundNumber: "CO",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:02:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+19705603941",
        timeToAnswer: "00:00:01",
        timeToConnect: "00:00:10",
        revenue: 55.0,
      },
      {
        id: "call15",
        callDate: "Jun 20 01:11:03 PM",
        inboundNumber: "MO",
        geoSubDivision: "",
        hangup: "circle",
        duplicate: false,
        connected: false,
        recording: "Click to Filter",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+16362756446",
        timeToAnswer: "00:00:02",
        timeToConnect: "00:00:10",
        revenue: 55.0,
      },
      {
        id: "call16",
        callDate: "Jun 25 11:31:21 AM",
        inboundNumber: "LA",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:03:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+13378423620",
        timeToAnswer: "00:00:02",
        timeToConnect: "00:00:08",
        revenue: 55.0,
      },
      {
        id: "call17",
        callDate: "Jun 11 03:46:04 PM",
        inboundNumber: "FL",
        geoSubDivision: "",
        hangup: "phone",
        duplicate: false,
        connected: true,
        recording: "00:00:...",
        userQuality: "",
        publisher: "Sunday Digital",
        callerId: "+19046491905",
        timeToAnswer: "00:00:00",
        timeToConnect: "00:00:09",
        revenue: 55.0,
      },
    ]

    return NextResponse.json(callDetailsData)
  } catch (error) {
    console.error("Error in call details endpoint:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}
